name: ghrs
on:
  schedule:
    # Run this once per day.
    # The specific hour is interpreted in UTC time zone.
    # Do this towards the end of the UTC day.
    - cron: "0 23 * * *"
  workflow_dispatch: # Allow for running this manually.

jobs:
  j1:
    name: github-repo-stats
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # The repositories to generate reports for.
        statsRepo: ['IceFireDB/redhub', 'RedTimeDB/RedTimeProxy']
      # Do not cancel&fail all remaining jobs upon first job failure.
      fail-fast: false
      # Help avoid commit conflicts. Note(JP): this should not be
      # necessary anymore, feedback appreciated
      max-parallel: 1
    steps:
      - name: github-repo-stats
        uses: jgehrcke/github-repo-stats@v1.4.2
        with:
          ghpagesprefix: https://jchicode.github.io/ghrs
          # Define the target repository, the repo to fetch
          # stats for and to generate the report for.
          repository: ${{ matrix.statsRepo }}
          # Required token privileges: Can read the target
          # repo, and can push to the repository this
          # workflow file lives in (to store data and
          # the report files).
          ghtoken: ${{ secrets.ghrs_github_api_token }}
          # Data branch: Branch to push data to (in the data repo).
          databranch: main
